language: python
python:
  - 2.7
install:
  - pip install --upgrade setuptools
  - pip install --upgrade pip
  - pip install -r requirements.txt
script:
  - mkdir -p var
  - export PYTHONPATH=`pwd`:$PYTHONPATH
  - py.test DanceCatTest/test_dance_cat_console.py --pep8 DanceCatConsole -v --cov DanceCatConsole --cov-report term-missing
after_success: coveralls
