language: python
python:
  - 2.7
install:
  - pip install --upgrade setuptools
  - pip install --upgrade pip
  - pip install -r requirements.txt
script:
  - mkdir -p var
  - export PYTHONPATH=`pwd`:$PYTHONPATH
  - py.test tests --pep8 DanceCats -v --cov DanceCats --cov-report term-missing
branches:
  only:
    - /^v\d+\.\d+(\.\d+)?$/
